/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenges;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String giveIceCream(String name, String flavor) {
        return "Give " + name + " " +  flavor + " ice cream";
    }
}
