/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenges;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testGiveIceCream() {
        Library library = new Library();
        String name = "Bade";
        String flavor = "Pistasio";

        String output = library.giveIceCream(name, flavor);

        assertEquals(output, "Give Bade Pistasio ice cream");
    }
}
